# Generated by Django 5.0.2 on 2025-10-29 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0002_alter_album_options_alter_artist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('spotify_username', models.CharField(blank=True, max_length=255)),
                ('spotify_email', models.EmailField(blank=True, max_length=254)),
                ('spotify_display_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField()),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('spotify_profile_url', models.URLField(blank=True, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('is_connected', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserListeningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_artists_short_term', models.JSONField(blank=True, default=list)),
                ('top_artists_medium_term', models.JSONField(blank=True, default=list)),
                ('top_artists_long_term', models.JSONField(blank=True, default=list)),
                ('top_tracks_short_term', models.JSONField(blank=True, default=list)),
                ('top_tracks_medium_term', models.JSONField(blank=True, default=list)),
                ('top_tracks_long_term', models.JSONField(blank=True, default=list)),
                ('total_artists_followed', models.IntegerField(default=0)),
                ('total_playlists', models.IntegerField(default=0)),
                ('total_saved_tracks', models.IntegerField(default=0)),
                ('recently_played_tracks', models.JSONField(blank=True, default=list)),
                ('favorite_genres', models.JSONField(blank=True, default=list)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('synced_short_term', models.DateTimeField(blank=True, null=True)),
                ('synced_medium_term', models.DateTimeField(blank=True, null=True)),
                ('synced_long_term', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listening_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
        migrations.CreateModel(
            name='UserListeningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(blank=True, max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255)),
                ('played_at', models.DateTimeField()),
                ('duration_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SyroMusic.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['-played_at'], name='SyroMusic_u_played__df89aa_idx'), models.Index(fields=['user', '-played_at'], name='SyroMusic_u_user_id_ce40c8_idx')],
            },
        ),
    ]
