# Generated by Django 5.0.2 on 2025-10-29 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0003_spotifyuser_userlisteningstats_userlisteningactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_tracks', models.JSONField(blank=True, default=list, help_text='List of track objects in queue order')),
                ('current_index', models.IntegerField(default=0)),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('repeat_mode', models.CharField(choices=[('off', 'No Repeat'), ('context', 'Repeat All'), ('track', 'Repeat One')], default='off', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('volume_percent', models.IntegerField(default=100)),
                ('is_private_session', models.BooleanField(default=False)),
                ('supports_volume', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='NowPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(blank=True, max_length=255)),
                ('track_name', models.CharField(blank=True, max_length=255)),
                ('artist_name', models.CharField(blank=True, max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255)),
                ('album_image_url', models.URLField(blank=True, null=True)),
                ('spotify_track_url', models.URLField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('progress_ms', models.IntegerField(default=0)),
                ('is_playing', models.BooleanField(default=False)),
                ('is_explicit', models.BooleanField(default=False)),
                ('context_type', models.CharField(blank=True, max_length=50)),
                ('context_id', models.CharField(blank=True, max_length=255)),
                ('context_name', models.CharField(blank=True, max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='now_playing', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SyroMusic.spotifydevice')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
