# Generated by Django 5.0.2 on 2025-10-30 02:23

import SyroMusic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0004_playbackqueue_spotifydevice_nowplaying'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='access_token',
            field=SyroMusic.models.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=SyroMusic.models.EncryptedField(blank=True, null=True),
        ),
    ]
