# Generated by Django 5.0.2 on 2025-11-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0007_userprofile_is_public_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='color_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='dominant_color',
            field=models.CharField(blank=True, db_index=True, default='#1a1a2e', max_length=7),
        ),
    ]
