# Generated by Django 5.0.2 on 2025-11-26 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0008_album_color_extracted_at_album_dominant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='SyroMusic.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
