# Generated by Django 5.0.2 on 2025-11-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0009_song_artist_song_duration_ms_song_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
