# Generated by Django 5.0.2 on 2025-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0010_album_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackhistoryanalytics',
            name='estimated_alltime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playbackhistoryanalytics',
            name='total_listening_minutes_this_year',
            field=models.IntegerField(default=0),
        ),
    ]
