# Generated by Django 5.0.2 on 2026-03-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyroMusic', '0011_playbackhistoryanalytics_estimated_alltime_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
